title: 我的个人博客
email: your-email@example.com
description: >-
  欢迎来到我的个人博客！这里记录我的学习笔记和技术分享。
baseurl: ""
url: "https://yyty947.github.io"
github_username:  yyty947

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
